Add lib folder to test directory hierarchy
`lib` folder added to `src/test/resources/project2/TelosysTools`.

A `.gitignore` file has been added to allow addition of the folder (git does not allow addition of empty folder).

This fix failure in test execution:
```
org.telosys.tools.commons.TelosysToolsException: Libraries folder : '/home/antoine/workspace/projects/telosys/telosys-tools-repository/src/test/resources/project2/TelosysTools/lib' not found
```